name    'martezr-windows_disable_ipv6'
version '0.1.0'
source ''
author ''
license ''
summary ''
description ''
project_page ''

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
dependency 'puppetlabs-registry', '>=0.1.1'
dependency 'puppetlabs-stdlib', '>=4.1.0'
dependency 'puppetlabs-reboot', '>=0.1.5'
dependency 'puppetlabs-reboot', ''
